Repository TUM-Dev/gocast, pull requests merged in 2021-12, with the labels that each got.

#154 Introduce staticcheck as a static analysis tool
  .github/dependabot.yml
  .github/workflows/staticcheck.yml
  .pre-commit-config.yaml
  README.md
  api/chat.go
  api/courses.go
  api/lecture_halls.go
  api/users.go
  api_grpc/worker.go
  app/server/main.go
  dao/ingest_server.go
  model/user.go
  staticcheck.conf
  tools/camera/camera.go
  tools/cameras.go
  tools/functions.go
  tools/tum/campus-online-base.go
  tools/tum/ldap.go
  web/index.go
  web/router.go
  web/user.go
Labels: enhancement, go, feature :sparkles:

#169 Remove quotation marks
  variables-backend.example.env
Labels: documentation

#168 Refactor and lint typescript
  .github/workflows/eslint.yml
  .idea/jsLinters/eslint.xml
  .idea/prettier.xml
  README.md
  web/.eslintrc
  web/.prettierrc.js
  web/package-lock.json
  web/package.json
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
  web/ts/admin.ts
  web/ts/course-import.ts
  web/ts/create-course.ts
  web/ts/edit-course.ts
  web/ts/global.ts
  web/ts/lecture-hall-management.ts
  web/ts/lecture-units.ts
  web/ts/onboarding.ts
  web/ts/schedule.ts
  web/ts/server-notifications.ts
  web/ts/stats.ts
  web/ts/watch-admin.ts
  web/ts/watch.ts
Labels: enhancement, javascript

#173 Server chat notifications
  api/chat.go
  api/wsHub.go
  tools/cache.go
  tools/config.go
  web/ts/watch.ts
Labels: ready

#183 use viper & yaml for configurations
  api/courses.go
  api/lecture_halls.go
  api/stream.go
  api/users.go
  api_grpc/worker.go
  app/server/main.go
  config.yaml
  go.mod
  go.sum
  tools/cameras.go
  tools/config.go
  tools/email.go
  tools/functions.go
  tools/tum/campus-online-base.go
  tools/tum/events.go
  tools/tum/ldap.go
  tools/tum/students.go
  tumlive.example.service
  variables-backend.example.env
  web/router.go
Labels: ready

#184 Deploy PRs to test server
  .github/workflows/ts-deploy.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement

#153 Improve model and dao
  api/chat.go
  api/users.go
  api_grpc/worker.go
  app/server/main.go
  dao/chat.go
  dao/courses.go
  dao/statistics.go
  dao/streams.go
  dao/worker.go
  model/camera_preset.go
  model/chat.go
  model/course.go
  model/file.go
  model/lecture_hall.go
  model/mail.go
  model/progress.go
  model/register_link.go
  model/server-notification.go
  model/shortlink.go
  model/stat.go
  model/stream-name.go
  model/stream-unit.go
  model/stream.go
  model/user.go
  model/worker.go
  web/ts/watch.ts
Labels: enhancement

#188 Optimize lecture schedule loading time
  api/lecture_halls.go
  api/sexy.go
  api/template/ical.gotemplate
  dao/courses.go
  dao/lecture_halls.go
  model/stream.go
Labels: ready

#170 Make streams visible that are starting soon
  .idea/jsLibraryMappings.xml
  app/server/main.go
  model/course.go
  model/stream.go
  web/tailwind.config.js
  web/template/course-card.gohtml
  web/template/course_list.gohtml
  web/template/index.gohtml
  web/template/watch.gohtml
  web/ts/global.ts
  web/ts/watch.ts
Labels: enhancement, go, UX, UI, ready

#197 Improve About
  web/template/about.gohtml
Labels: priority:low, ready

#196 Set fixed go hook revision
  .pre-commit-config.yaml
Labels: dependencies, priority:low, ready
