Repository TUM-Dev/gocast, pull requests merged in 2022-07, with the labels that each got.

#535 Keep current section displayed & VS Mobile UI
  api/worker_grpc.go
  web/template/partial/course/manage/edit-video-sections.gohtml
  web/template/partial/stream/video-sections.gohtml
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
  web/ts/VideoSection.ts
  web/ts/entry/admins.ts
  web/ts/entry/video.ts
  web/ts/video-sections.ts
Labels: Open Source Lab, awaiting feedback

#568 Search endpoint testing
  api/search.go
  api/search_test.go
Labels: Open Source Lab, awaiting feedback

#578 Fix elForSpot Alpine Error
  web/template/partial/stream/video-sections.gohtml
  web/ts/global.ts
  web/ts/video-sections.ts
Labels: Open Source Lab

#524 Lecture Hall Endpoint Testing
  api/lecture_halls.go
  api/lecture_halls_test.go
  tools/testutils/testdata.go
  tools/testutils/testutils.go
Labels: awaiting feedback

#475 OCR Keyword extraction
  api/worker_grpc.go
  cmd/tumlive/tumlive.go
  dao/dao_base.go
  dao/keyword.go
  dao/search.go
  go.work.sum
  mock_dao/keyword.go
  model/keyword.go
  model/stream.go
  worker/Dockerfile
  worker/api/api.proto
  worker/go.mod
  worker/go.sum
  worker/ocr/ocr.go
  worker/pb/api.pb.go
  worker/pb/api_grpc.pb.go
  worker/worker/request_handlers.go
  worker/worker/status.go
Labels: Open Source Lab

#585 Add "Copy HSL URL" button next to each video in course overview
  web/template/partial/stream/actions.gohtml
  web/template/vod_course_list.gohtml
  web/ts/global.ts
Labels: UX, UI

#583 Remove hls quality selector
  web/package-lock.json
  web/package.json
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
Labels: dependencies

#588 Fix 'follow sections' jumps to not existing page
  web/ts/video-sections.ts
Labels: bug, Open Source Lab

#549 Course Endpoint Testing
  api/audit_test.go
  api/courses.go
  api/courses_test.go
  api/router.go
  api/sexy.go
  api/sexy_test.go
  api/stream_test.go
  dao/progress.go
  dao/streams.go
  mock_dao/streams.go
  tools/testutils/testdata.go
  tools/testutils/testutils.go
Labels: awaiting feedback

#541 Integrate keywords into search
  mock_dao/keyword.go
Labels: Open Source Lab, awaiting feedback

#577 Consistent Error Handling
  api/audit.go
  api/chat.go
  api/courseimport.go
  api/courses.go
  api/courses_test.go
  api/download.go
  api/download_ics.go
  api/download_ics_test.go
  api/info-pages.go
  api/info-pages_test.go
  api/lecture_halls.go
  api/lecture_halls_test.go
  api/notifications.go
  api/progress.go
  api/progress_test.go
  api/router.go
  api/search.go
  api/server-notifications.go
  api/statistics.go
  api/statistics_test.go
  api/stream.go
  api/stream_test.go
  api/token.go
  api/users.go
  api/users_test.go
  api/worker.go
  api/worker_test.go
  tools/api-errors.go
  tools/testutils/testutils.go
Labels: enhancement, awaiting feedback

#606 Retry dial-in after dynamic backoff
  worker/cfg/cfg.go
  worker/client/main.go
  worker/cmd/worker/worker.go
Labels: go, worker
