Repository TUM-Dev/gocast, pull requests merged in 2022-01, with the labels that each got.

#195 fix activity overview statistics
  .github/workflows/go-test.yml
  dao/statistics.go
  tools/timing/time.go
  tools/timing/time_test.go
Labels: ready

#217 Improve timer for waiting rooms
  web/template/course-card.gohtml
  web/template/watch.gohtml
  web/ts/global.ts
Labels: enhancement, ready, testserver

#198 closable chat and error on disconnect
  web/assets/css/main.css
  web/template/partial/stream/chat.gohtml
  web/template/watch.gohtml
  web/ts/chat.ts
  web/ts/watch.ts
Labels: ready

#230 Update course page
  dao/courses.go
  model/course.go
  model/stream.go
  web/template/course.gohtml
  web/template/header.gohtml
  web/template/index.gohtml
  web/template/planned_course_list.gohtml
  web/template/vod_course_list.gohtml
Labels: ready

#187 End streams early
  api/stream.go
  api/worker.go
  api/worker_grpc.go
  app/server/main.go
  dao/streams.go
  go.mod
  go.sum
  model/stream.go
  web/assets/css/main.css
  web/template/partial/stream/download.gohtml
  web/template/watch.gohtml
  web/ts/global.ts
Labels: go, feature :sparkles:, UI, ready

#248 don't scroll down chat when scrolled up
  web/template/partial/stream/chat.gohtml
  web/ts/watch.ts
Labels: enhancement, ready

#251 Prevent event-stacking of progressReports by using setTimeout + recursion
  web/ts/TUMLiveVjs.ts
Labels: bug, ready

#247 fix panic on admin page when not logged in
  tools/middlewares.go
Labels: bug, priority:high

#257 bundle version tag into docker container binary
  .github/workflows/ts-deploy.yml
  Dockerfile
Labels: ready, testserver

#254 Feature: Reply to chat messages
  api/chat.go
  dao/chat.go
  dao/streams.go
  model/chat.go
  web/template/partial/stream/chat.gohtml
  web/template/partial/stream/chat_message.gohtml
  web/template/watch.gohtml
  web/ts/watch.ts
  web/watch.go
Labels: feature :sparkles:, ready

#246 reject course creation if slug already exists for semester
  api/courses.go
  dao/courses.go
  tools/middlewares.go
Labels: bug

#155 Improve front end infrastructure
  web/index.go
  web/package-lock.json
  web/package.json
  web/template/about.gohtml
  web/template/admin/admin.gohtml
  web/template/admin/admin_tabs/course-import.gohtml
  web/template/admin/admin_tabs/create-course.gohtml
  web/template/admin/admin_tabs/create-lecture_halls.gohtml
  web/template/admin/admin_tabs/edit-course.gohtml
  web/template/admin/admin_tabs/lecture_halls.gohtml
  web/template/admin/admin_tabs/schedule.gohtml
  web/template/admin/admin_tabs/server-notifications.gohtml
  web/template/admin/admin_tabs/stats.gohtml
  web/template/admin/admin_tabs/users.gohtml
  web/template/admin/admin_tabs/workers.gohtml
  web/template/admin/course_settings.gohtml
  web/template/admin/lecture-cut.gohtml
  web/template/admin/lecture-units.gohtml
  web/template/course-card.gohtml
  web/template/headImports.gohtml
  web/template/header.gohtml
  web/template/login.gohtml
  web/template/onboarding.gohtml
  web/template/partial/stream/chat.gohtml
  web/template/passwordreset.gohtml
  web/template/video_only.gohtml
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
  web/ts/admin.ts
  web/ts/chat.ts
  web/ts/course-import.ts
  web/ts/create-course.ts
  web/ts/edit-course.ts
  web/ts/entry/admins.ts
  web/ts/entry/user.ts
  web/ts/entry/video.ts
  web/ts/global.ts
  web/ts/lecture-hall-management.ts
  web/ts/lecture-units.ts
  web/ts/onboarding.ts
  web/ts/schedule.ts
  web/ts/server-notifications.ts
  web/ts/stats.ts
  web/ts/watch-admin.ts
  web/ts/watch.ts
  web/tsconfig.json
  web/user.go
  web/webpack.common.js
  web/webpack.dev.js
  web/webpack.prod.js
Labels: enhancement, javascript, ready

#268 buffer stream progresses
  api/progress.go
  dao/progress.go
Labels: enhancement
