Repository TUM-Dev/gocast, pull requests merged in 2022-11, with the labels that each got.

#777 Revert "Include Timestamp in URL (#633)"
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
  web/ts/global.ts
Labels: priority:urgent

#753 Add KaTeX
  web/package-lock.json
  web/package.json
  web/template/headImports.gohtml
  web/template/partial/stream/chat/chat.gohtml
  web/template/partial/stream/chat/chat_message.gohtml
  web/template/watch.gohtml
Labels: UX, feature :sparkles:, UI, hacktoberfest-accepted

#785 Remove 'paused' banner
  web/template/watch.gohtml
Labels: bug

#787 Fix @-ing others
  web/template/partial/stream/chat/chat.gohtml
Labels: bug

#784 Fix poll close-button
  web/template/partial/stream/chat/chat.gohtml
Labels: bug

#795 Remove server messages
  api/wsHub.go
Labels: enhancement

#786 Add un-approve/retract message
  api/chat.go
  dao/chat.go
  mock_dao/chat.go
  mock_dao/prefetchedCourse.go
  model/chat.go
  web/template/partial/stream/chat/chat.gohtml
  web/template/partial/stream/chat/chat_message.gohtml
  web/ts/chat/Chat.ts
  web/ts/watch.ts
Labels: feature :sparkles:
