Repository TUM-Dev/gocast, pull requests merged in 2022-10, with the labels that each got.

#580 Watch page UI updates
  web/assets/css/main.css
  web/template/header.gohtml
  web/template/partial/download.gohtml
  web/template/partial/stream/actions.gohtml
  web/template/partial/stream/attachments.gohtml
  web/template/partial/stream/chat/chat.gohtml
  web/template/partial/stream/chat/chat_message.gohtml
  web/template/partial/stream/chat/chatprompts.gohtml
  web/template/partial/stream/chat/emojipromt.gohtml
  web/template/partial/stream/video-sections.gohtml
  web/template/partial/stream/watch-info.gohtml
  web/template/popup-chat.gohtml
  web/template/watch.gohtml
  web/ts/chat/Poll.ts
  web/ts/video-sections.ts
  web/ts/watch.ts
Labels: Open Source Lab, awaiting feedback

#710 Remove Google Cast toggle
  api/router.go
  api/users.go
  dao/migrations/202208100.go
  dao/migrator.go
  model/user.go
  web/template/user-settings.gohtml
  web/ts/user-settings.ts
Labels: priority:low

#728 Fix chat misplacement
  web/assets/css/main.css
  web/template/partial/stream/chat/chat_message.gohtml
Labels: bug

#743 Add additional Makefile targets and phony targets
  Makefile
  worker/Makefile
Labels: code quality
