Repository TUM-Dev/gocast, pull requests merged in 2022-02, with the labels that each got.

#299 Add popup chat
  tools/middlewares.go
  web/assets/css/main.css
  web/popup.go
  web/router.go
  web/template/partial/stream/chat/chat.gohtml
  web/template/partial/stream/chat/chat_message.gohtml
  web/template/popup-chat.gohtml
  web/template/watch.gohtml
  web/ts/chat.ts
  web/ts/watch.ts
  web/watch.go
Labels: ready

#308 Fix download popup positioning
  web/template/partial/stream/download.gohtml
Labels: bug, ready

#309 use absolute link for chat popout
  web/template/partial/stream/chat/chat.gohtml
  web/ts/chat.ts
Labels: bug

#311 Fix button title
  web/template/partial/stream/chat/chat.gohtml
Labels: bug, UI
