Repository TUM-Dev/gocast, pull requests merged in 2022-09, with the labels that each got.

#598 Restructure courses router definitions
  api/courses.go
Labels: code quality

#664 Update go, remove deprecations and house-keeping
  .github/workflows/go-test.yml
  .github/workflows/staticcheck.yml
  Dockerfile
  api/courses.go
  api/worker_grpc.go
  worker/Dockerfile
  worker/edge/Dockerfile
  worker/edge/edge.go
  worker/edge/go.mod
  worker/go.mod
  worker/ocr/ocr.go
  worker/rest/vod_upload.go
  worker/worker/record.go
  worker/worker/request_handlers.go
  worker/worker/request_handlers_test.go
  worker/worker/status.go
  worker/worker/upload.go
  worker/worker/upload_test.go
  worker/worker/waveform.go
Labels: docker, code quality

#681 Improve robustness of watched counter
  dao/streams.go
  web/course.go
  web/template/vod_course_list.gohtml
  web/ts/course-overview.ts
Labels: bug

#683 Also fetch students for upcoming courses
  dao/courses.go
  mock_dao/courses.go
  tools/tum/campus-online-base.go
Labels: bug, priority:high

#469 Presentation Only/Camera Only Streams
  api/courses.go
  api/courses_test.go
  api/worker_grpc.go
  model/camera_preset.go
  model/course.go
  tools/presets.go
  tools/testutils/testdata.go
  web/template/admin/admin_tabs/edit-course.gohtml
  web/template/partial/course/manage/camera-presets.gohtml
  web/template/partial/course/manage/lecture-hall-settings.gohtml
  web/template/vod_course_list.gohtml
  web/watch.go
Labels: Open Source Lab, awaiting feedback
