Repository TUM-Dev/gocast, pull requests merged in 2022-06, with the labels that each got.

#489 Separate link/s for data privacy statement and imprint + markdown
  api/info-pages.go
  api/router.go
  cmd/tumlive/tumlive.go
  dao/dao_base.go
  dao/info-page.go
  model/info-page.go
  web/admin.go
  web/assets/css/main.css
  web/index.go
  web/router.go
  web/template/admin/admin.gohtml
  web/template/admin/admin_tabs/info-pages.gohtml
  web/template/header.gohtml
  web/template/info-page.gohtml
  web/template/partial/info-dropdown.gohtml
  web/template/partial/theme-selector.gohtml
  web/template/semester-selection.gohtml
  web/ts/admin.ts
Labels: awaiting feedback

#478 Thumbnails on hover
  api/download.go
  api/stream.go
  api/worker_grpc.go
  dao/streams.go
  go.sum
  go.work.sum
  model/file.go
  model/stream.go
  web/assets/css/main.css
  web/package-lock.json
  web/package.json
  web/template/course_list.gohtml
  web/template/partial/stream/actions.gohtml
  web/template/video_only.gohtml
  web/template/vod_course_list.gohtml
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
  worker/Dockerfile
  worker/api/api.proto
  worker/go.mod
  worker/go.sum
  worker/pb/api.pb.go
  worker/pb/api_grpc.pb.go
  worker/worker/notify.go
  worker/worker/request_handlers.go
  worker/worker/request_handlers_test.go
  worker/worker/status.go
  worker/worker/stream.go
  worker/worker/thumbnails.go
Labels: feature :sparkles:, worker

#523 Improve watch page UI
  api/courses.go
  model/stream.go
  tools/truncate.go
  web/template/course-overview.gohtml
  web/template/partial/stream/actions.gohtml
  web/template/partial/stream/alert-modal.gohtml
  web/template/partial/stream/video-sections.gohtml
  web/template/partial/stream/watch-info.gohtml
  web/template/watch.gohtml
  web/watch.go
Labels: UX, UI

#527 Feat/audit log
  api/audit.go
  api/audit_test.go
  api/courses.go
  api/router.go
  api/stream.go
  api/stream_test.go
  cmd/tumlive/tumlive.go
  dao/audit.go
  dao/dao_base.go
  mock_dao/audit.go
  model/audit.go
  model/user.go
  tools/testutils/testdata.go
  web/admin.go
  web/router.go
  web/template/admin/admin.gohtml
  web/template/admin/admin_tabs/audits.gohtml
  web/ts/audits.ts
  web/ts/entry/admins.ts
Labels: work in progress
