Repository TUM-Dev/gocast, pull requests merged in 2022-05, with the labels that each got.

#425 change source map to eval-source-map
  web/webpack.dev.js
Labels: Open Source Lab

#363 Video Sections
  api/stream.go
  cmd/tumlive/tumlive.go
  dao/streams.go
  dao/video-section.go
  docs/docs/video-img/sections-on-watch-page.jpg
  docs/docs/video-img/video-sections.jpg
  docs/docs/video.md
  mock_dao/video-section.go
  model/stream.go
  model/video-section.go
  web/template/admin/admin_tabs/edit-course.gohtml
  web/template/admin/edit-video-sections.gohtml
  web/template/partial/stream/video-sections.gohtml
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
  web/ts/VideoSection.ts
  web/ts/entry/admins.ts
Labels: ready

#444 Video Section fixes
  dao/streams.go
  web/template/partial/course/manage/edit-video-sections.gohtml
  web/template/watch.gohtml
  web/ts/VideoSection.ts
Labels: ready, awaiting feedback

#443 fix course admin json parsing
  go.mod
  go.sum
  model/course.go
  model/stream.go
  tools/template_executor.go
  web/router.go
  web/template/partial/course/manage/course-lecture-management.gohtml
  web/template/partial/course/manage/lecture-management-card.gohtml
  web/ts/edit-course.ts
Labels: priority:high

#445 add shared run configurations
  .idea/runConfigurations/all.xml
  .idea/runConfigurations/build_dev.xml
  .idea/runConfigurations/build_production.xml
  .idea/runConfigurations/clean.xml
  .idea/runConfigurations/lint.xml
  .idea/runConfigurations/lint_fix.xml
  .idea/runConfigurations/postinstall.xml
  .idea/runConfigurations/run_dev.xml
  .idea/runConfigurations/run_production.xml
  .idea/runConfigurations/run_tumlive_go.xml
  .idea/runConfigurations/tailwind_compile.xml
Labels: enhancement, Open Source Lab

#455 add dao wrapper to grpc worker api
  api/worker_grpc.go
Labels: bug, priority:high

#446 Support AirPlay
  web/package-lock.json
  web/package.json
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
Labels: enhancement, Open Source Lab

#463 generate new stream key for each stream in lecture series
  api/courses.go
Labels: bug, priority:high

#467 Improve filtering watched videos
  web/template/course-overview.gohtml
  web/template/vod_course_list.gohtml
  web/ts/course-overview.ts
Labels: enhancement, UX, UI

#395 Slide upload for presentations etc
  api/download.go
  api/stream.go
  dao/file.go
  go.mod
  go.work.sum
  mock_dao/file.go
  mock_dao/streams.go
  model/file.go
  model/stream.go
  web/template/admin/admin_tabs/edit-course.gohtml
  web/template/partial/course/manage/lecture-management-card.gohtml
  web/template/partial/stream/actions.gohtml
  web/template/partial/stream/attachments.gohtml
  web/ts/admin.ts
  web/ts/edit-course.ts
Labels: ready, Open Source Lab, awaiting feedback

#479 Fix video-js-hls-quality-selector deprecation warning
  web/package-lock.json
  web/package.json
Labels: bug, dependencies

#473 Highlight current video section on watch page
  api/stream.go
  web/template/partial/course/manage/edit-video-sections.gohtml
  web/template/partial/stream/video-sections.gohtml
  web/ts/TUMLiveVjs.ts
  web/ts/VideoSection.ts
  web/ts/global.ts
Labels: Open Source Lab

#484 Edit button for course and stream on their pages
  web/template/course-overview.gohtml
  web/template/watch.gohtml
Labels: awaiting feedback

#396 Search through lectures
  .idea/runConfigurations/run_tumlive_go.xml
  api/router.go
  api/search.go
  api/stream.go
  dao/dao_base.go
  dao/search.go
  go.mod
  go.sum
  mock_dao/chat.go
  mock_dao/streams.go
  model/chat.go
  model/stream.go
  model/video-section.go
  web/template/course-overview.gohtml
  web/ts/entry/user.ts
  web/ts/stream-search.ts
Labels: Open Source Lab, awaiting feedback
