Repository TUM-Dev/gocast, pull requests merged in 2023-01, with the labels that each got.

#868 Dependency updates
  Dockerfile
  go.mod
  go.sum
  go.work.sum
  web/package-lock.json
  web/package.json
  worker/go.mod
  worker/go.sum
Labels: dependencies, docker

#603 Multiple Synced Players
  web/assets/css/main.css
  web/package-lock.json
  web/package.json
  web/template/partial/stream/actions.gohtml
  web/template/video_only.gohtml
  web/template/watch.gohtml
  web/ts/TUMLiveVjs.ts
  web/ts/chat/Chat.ts
  web/ts/entry/video.ts
  web/ts/lecture-units.ts
  web/ts/splitview.ts
  web/ts/watch.ts
  web/tsconfig.json
Labels: feature :sparkles:

#841 Add copying of up-to-date timestamps via context menu
  Makefile
  web/assets/css/main.css
  web/template/watch.gohtml
  web/ts/watch.ts
Labels: enhancement

#881 Fix Alpine Bookmarks Error
  web/template/watch.gohtml
  web/ts/bookmarks.ts
Labels: bug

#880 Unsplit mobile and desktop action bar
  web/template/partial/stream/actions.gohtml
  web/template/watch.gohtml
Labels: UI, code quality

#883 Add autocomplete
  web/template/login.gohtml
Labels: code quality
