Repository TUM-Dev/gocast, pull requests merged in 2023-12, with the labels that each got.

#1258 I praktikum 36 user endpoints
  api_v2/README.md
  api_v2/api_v2.proto
  api_v2/authorization.go
  api_v2/course.go
  api_v2/docs/api_v2.swagger.json
  api_v2/errors/errors.go
  api_v2/helpers/parser.go
  api_v2/protobuf/api_v2.pb.go
  api_v2/protobuf/api_v2.pb.gw.go
  api_v2/protobuf/api_v2_grpc.pb.go
  api_v2/services/course_service.go
  api_v2/services/user_service.go
  api_v2/user.go
  docker-compose.yml
  docs/static/tum-live-starter.sql
Labels: go, docker

#1251 Watch page: Align sidebars with the watch wrapper
  web/template/watch.gohtml
Labels: UI

#1273 I praktikum 73 push notifications
  api/worker_grpc.go
  api_v2/api_v2.proto
  api_v2/docs/api_v2.swagger.json
  api_v2/notifications.go
  api_v2/protobuf/api_v2.pb.go
  api_v2/protobuf/api_v2.pb.gw.go
  api_v2/protobuf/api_v2_grpc.pb.go
  api_v2/services/notification_service.go
  api_v2/services/user_service.go
  api_v2/stream.go
  api_v2/user.go
  cmd/tumlive/tumlive.go
  config.yaml
  dao/courses.go
  go.mod
  go.sum
  model/user.go
  tools/config.go
Labels: dependencies, go, feature :sparkles:

#1274 Revise golangci-lint configuration
  .gitattributes
  .github/workflows/golangci-lint.yml
  .golangci.yml
  api/maintenance.go
  api/server-notifications.go
  api/users.go
  cmd/tumlive/tumlive.go
  model/user.go
Labels: code quality

#1277 IPraktikum progress fetching and marking as watched
  .gitignore
  api_v2/api_v2.proto
  api_v2/docs/api_v2.swagger.json
  api_v2/helpers/parser.go
  api_v2/protobuf/api_v2.pb.go
  api_v2/protobuf/api_v2.pb.gw.go
  api_v2/protobuf/api_v2_grpc.pb.go
  api_v2/services/stream_service.go
  api_v2/stream.go
  go.mod
  go.sum
  go.work
Labels: enhancement, go

#1276 IPraktikum get and patch user settings
  .gitignore
  api_v2/api_v2.proto
  api_v2/docs/api_v2.swagger.json
  api_v2/helpers/parser.go
  api_v2/protobuf/api_v2.pb.go
  api_v2/protobuf/api_v2.pb.gw.go
  api_v2/protobuf/api_v2_grpc.pb.go
  api_v2/services/user_service.go
  api_v2/user.go
Labels: enhancement, go

#1245 Fixed and optimized several issues in the front end of the course settings page
  web/template/admin/admin_tabs/create-course.gohtml
  web/template/admin/admin_tabs/edit-course.gohtml
  web/template/partial/course/manage/course_actions.gohtml
  web/template/partial/course/manage/create-lecture-form-slides/lecture-type-slide.gohtml
  web/template/partial/course/manage/create-lecture-form.gohtml
  web/template/partial/course/manage/semester-selection.gohtml
  web/ts/edit-course.ts
Labels: UI
